name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential cmake libboost-all-dev libopencv-dev libjsoncpp-dev
      - name: Build
        run: |
          cmake .
          make
      - name: Test
        run: |
          ./gtest
